apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: output-pipeline
spec:
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: build
      taskRef:
        name: build
      resources:
        inputs:
          - name: workspace
            resource: source-repo
        outputs:
          - name: workspace
            resource: source-repo
    - name: then-check                 # 2.  check file exists
      taskRef:
        name: check-stuff-file-exists
      resources:
        inputs:
          - name: workspace
            resource: source-repo
            from: [build]
